version: '3.8'
services:
  zyzzdb:
    image: postgres:11.1
    container_name: zyzzdb
    environment:
      POSTGRES_PASSWORD: zyzzpass
      POSTGRES_DB: zyzzdb
      POSTGRES_USER: zyzzdb
    ports:
      - 5432:5432
    networks:
      - app-tier
    volumes:

      - ./postgres:/docker-entrypoint-initdb.d

  zyzzbot:
    image: zyzzbot
    container_name: zyzzbot
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - zyzzdb
    ports:
      - "80:80"
    networks:
      - app-tier
    volumes:
      - .:/opt/
    environment:
      - PORT=80

networks:
  app-tier:
    driver: bridge
